"""empty message

Revision ID: 0bc62149ba37
Revises: 258ef04d3833
Create Date: 2025-05-28 19:48:25.360492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bc62149ba37'
down_revision = '258ef04d3833'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('static_quantity', sa.Integer, nullable=False, default=0),
    )
    
    # ### end Alembic commands ###


def downgrade():
    op.add_column('Products', sa.Column('static_quantity', sa.Integer, nullable=False, default=0),
    )