"""empty message

Revision ID: 114187a95cdf
Revises: 80564c51cd36
Create Date: 2025-05-11 19:42:49.025422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '114187a95cdf'
down_revision = '80564c51cd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_dayli_confirmed', sa.Boolean(), nullable=False),
    )
    
    # ### end Alembic commands ###


def downgrade():
    op.add_column('Users', sa.Column('is_dayli_confirmed', sa.Boolean(), nullable=False),
    )