"""empty message

Revision ID: 258ef04d3833
Revises: a302e30782dd
Create Date: 2025-05-24 21:07:08.749580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '258ef04d3833'
down_revision = 'a302e30782dd'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # op.create_table('Leads',
    # sa.Column('email', sa.String(200), nullable=False),
    # sa.Column('name', sa.String(250), nullable=False),
    # sa.Column('number', sa.String(30), nullable=False),
    # sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    # sa.PrimaryKeyConstraint('email')
    # )

    op.drop_column('Users', 'total_registrations')
    
    # ### end Alembic commands ###


def downgrade():
    op.add_column('Users', sa.Column('total_registrations', sa.Integer(), nullable=False, server_default='0'))
    op.drop_table('Leads')