"""empty message

Revision ID: 44efd9393a4d
Revises: 49f6196897fe
Create Date: 2025-04-12 01:47:39.346840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44efd9393a4d'
down_revision = '49f6196897fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.Column('message', sa.String(length=700), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('Dates')
    # ### end Alembic commands ###
