"""empty message

Revision ID: 462241808271
Revises: 50c792080088
Create Date: 2025-04-10 21:31:45.101303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462241808271'
down_revision = '50c792080088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
