"""empty message

Revision ID: 50c792080088
Revises: bcc66d53f54f
Create Date: 2025-04-10 00:29:12.540383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50c792080088'
down_revision = 'bcc66d53f54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=700), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=450),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=450),
               existing_nullable=True)
        batch_op.drop_column('date')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
