"""empty message

Revision ID: 80564c51cd36
Revises: 9e3d82ac58d5
Create Date: 2025-05-10 23:06:28.947720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80564c51cd36'
down_revision = '9e3d82ac58d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', sa.Column('date', sa.Date(), nullable=False),
    )
    
    # ### end Alembic commands ###


def downgrade():
    op.alter_column('Users', sa.Column('date', sa.Date(), nullable=False),
    )
