"""empty message

Revision ID: 86662b442688
Revises: 
Create Date: 2025-03-26 20:54:30.507694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86662b442688'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=80), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=450), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
