"""empty message

Revision ID: a302e30782dd
Revises: a6aac8c7c9f8
Create Date: 2025-05-24 19:38:16.704575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a302e30782dd'
down_revision = 'a6aac8c7c9f8'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('total_registrations', sa.Integer, nullable=False, default=0),
    )
    
    # ### end Alembic commands ###


def downgrade():
    op.add_column('Users', sa.Column('total_registrations', sa.Integer, nullable=False, default=0),
    )