"""empty message

Revision ID: a6aac8c7c9f8
Revises: 114187a95cdf
Create Date: 2025-05-19 23:00:55.957028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6aac8c7c9f8'
down_revision = '114187a95cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Date Unavailable', sa.Column('product', sa.String(length=120), nullable=True),
    )
    
    # ### end Alembic commands ###


def downgrade():
    op.add_column('Date Unavailable', sa.Column('product', sa.String(length=120), nullable=True),
    )