"""primeira

Revision ID: bcc66d53f54f
Revises: 86662b442688
Create Date: 2025-04-02 22:45:43.181444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc66d53f54f'
down_revision = '86662b442688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=450), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
