"""empty message

Revision ID: d9ec2fb6c288
Revises: d9c099092e88
Create Date: 2025-05-09 19:41:38.593360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9ec2fb6c288'
down_revision = 'd9c099092e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('Calendar',
    # sa.Column('id', sa.BigInteger(), nullable=False),
    # sa.Column('date', sa.Date(), nullable=False),
    # sa.Column('day_quantity', sa.Integer(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('Date Unavailable',
    # sa.Column('id', sa.BigInteger(), nullable=False),
    # sa.Column('date', sa.Date(), nullable=False),
    # sa.Column('reason', sa.String(length=120), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('Dates',
    # sa.Column('id', sa.BigInteger(), nullable=False),
    # sa.Column('date', sa.Date(), nullable=False),
    # sa.Column('total_amount', sa.Float(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('Products',
    # sa.Column('id', sa.BigInteger(), nullable=False),
    # sa.Column('type', sa.Enum('PULA_PULA_MEDIO', 'PULA_PULA_GRANDE', 'CASA_BOLINHA_PEQUENA', 'CASA_BOLINHA_GRANDE', 'TOBOGA_INFLAVEL', name='types_products'), nullable=False),
    # sa.Column('description', sa.String(length=180), nullable=True),
    # sa.Column('quantity', sa.Integer(), nullable=True),
    # sa.Column('is_available', sa.Boolean(), nullable=True),
    # sa.Column('price', sa.Float(), nullable=True),
    # sa.Column('image', sa.String(length=250), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('products')
    # op.drop_table('dates')
    # op.drop_table('calendar')
    # op.drop_table('date unavailable')
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.drop_constraint('user_products_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_products_ibfk_3', 'products', ['product_id'], ['id'])

    op.create_table('date unavailable',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('calendar',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('day_quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dates',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('products',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.ENUM('PULA_PULA_MEDIO', 'PULA_PULA_GRANDE', 'CASA_BOLINHA_PEQUENA', 'CASA_BOLINHA_GRANDE', 'TOBOGA_INFLAVEL'), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Products')
    op.drop_table('Dates')
    op.drop_table('Date Unavailable')
    op.drop_table('Calendar')
    # ### end Alembic commands ###
